
# Deploy reddit app
- name: "Reddit App: Deploy application"
  hosts: all
  gather_facts: no
  remote_user: appuser


  tasks:
  - name: Remove me after adding real things
    git:
      repo: 'https://github.com/Artemmkin/reddit.git'
      dest: ~/reddit

  - name: install reddit
    shell: 'cd reddit && bundle install'

  # - name: update gems
  #   bundler:
  #     state: latest
  #     chdir: ~/reddit
