- name: Deploy App
  hosts: app
  tags: deploy-tag
  vars:
    deploy_user: appuser
  environment:
    PATH: '/home/{{ deploy_user }}/.rvm/gems/ruby-2.4.1/bin:/home/{{ deploy_user }}/.rvm/rubies/ruby-2.4.1/bin/:{{ ansible_env.PATH }}'

  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/Artemmkin/reddit.git'
        dest: "/home/{{ deploy_user }}/reddit"
        version: monolith
      notify: restart puma


    - name: bundle install
      bundler:
        state: present
        chdir: "/home/{{ deploy_user }}/reddit"


  handlers:
  - name: restart puma
    become: true
    systemd: name=puma state=restarted
