---

- name: install revert proxy nginx
  hosts: app
  become: yes
  vars:
    # nginx_user: "appuser"
    nginx_vhosts:
      - listen: "80"
        server_name: "35.240.49.93"
        extra_parameters: |
          location / {
            proxy_pass http://127.0.0.1:9292;
          }

  roles:
    - { role: geerlingguy.nginx }
