
# Work play for install mongodb
- name: "Reddit App: Install mongodb"
  hosts: all
  gather_facts: no
  remote_user: root

  tasks:

  - name: Install repo key
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: EA312927

  - name: Install repo
    shell: 'echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" > /etc/apt/sources.list.d/mongodb-org-3.2.list'


  - name: Install mongodb package
    apt: "name=mongodb-org state=present update_cache=yes"
