---

- name: Configure hosts and deploy application
  hosts: all
  vars:
    mongo_bind_ip: 0.0.0.0
    db_host: 10.132.15.195

  tasks:

  - name: Change mongo config file
    become: true
    template:
      src: templates/mongod.conf.j2
      dest: /etc/mongod.conf
      mode: 0644
    tags: db-tag
    notify: restart mongod

  - name: copy
    become: true
    copy:
      src: files/puma.service
      dest: /etc/systemd/system/puma.service
    notify: reload puma
    tags: app-tag


  - name: create  db_config
    become: true
    file:
      path: "/home/appuser/db_config"
      state: touch
    tags: app-tag

  - name: Add config for DB connection
    template:
      src: templates/db_config.j2
      dest: /home/appuser/db_config
    tags: app-tag

  - name: enable puma
    become: true
    systemd:
      name: puma
      enabled: yes
      state: started
      masked: no
    tags: app-tag

  - name: Clone reddit from github
    git:
      repo: 'https://github.com/Artemmkin/reddit.git'
      dest: ~/reddit
    tags: deploy-tag

  - name: install reddit
    shell: 'cd reddit && /home/appuser/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/bin/bundle install'
    tags: deploy-tag

  - name: update gems
    bundler:
      state: latest
      chdir: ~/reddit
    notify: restart puma
    tags: deploy-tag


  handlers:
  - name: restart mongod
    become: true
    service: name=mongod state=restarted

  - name: reload puma
    become: true
    systemd: name=puma state=reloaded

  - name: restart puma
    become: true
    systemd: name=puma state=restarted
